### ISSUE TITLE
models and weights

### ISSUE THREAD

**Issue by LiaoChengkk** [quickhdsdc/Point-Tracking-for-Displacement-Measurement-in-Railway-Applications#1]
Could you please upload the models and weights involved in your code?

**Comment by quickhdsdc** [comment]
Hi, there are two models in the folder "trained_models". I also upload some models with different settings. They should be the ones used in the paper. As far as I can recall, "LightPointNet_normal_Integral_L1" is the model of our method. The loss L1 is better than L2 and MSE. hope it can help you

**Comment by LiaoChengkk** [comment]
Thank you for your reply. But I still don't know how to get the.pt file such as LightPointNet_all.pt in train.py.

**Comment by LiaoChengkk** [comment]
Thank you for your reply, that will help me much!
